### ISSUE TITLE
Issue with two character keymap to enter normal mode

### ISSUE THREAD

**Issue by smjonas** [smilhey/ed-cmd.nvim#1]
Hi there, neat plugin! I use the following config:
```lua
  { "smilhey/ed-cmd.nvim", config = { cmdline = { keymaps = { edit = "ij" } } } },
```
However, there is an issue when I i type `ij` in to enter normal mode:

https://github.com/user-attachments/assets/b6d39fef-0f43-4380-8db8-5c12c933d4c0

In the recording, I am pressing `ij`, however after `j` is entered, normal mode is entered and the cursor moves one character to the left but the `i` from the mapping is not deleted.

Can this be fixed?

**Comment by smilhey** [comment]
Oh ! This is a case I had not thought about. Try setting this keymap instead passing it to setup : 

```lua
vim.keymap.set("c", "ij", function()
	require("ed-cmd.cmdline").enter_edit()
	vim.schedule(function()
		vim.cmd("silent norm lxh")
	end)
end, {})
```
does it solve the issue ?

**Comment by smjonas** [comment]
Thanks, that worked!
