### ISSUE TITLE
Able to assign 2 keymaps to exit the ed-cmd, and highlight issue

### ISSUE THREAD

**Issue by bassamsdata** [smilhey/ed-cmd.nvim#2]
Hello,

Thank you for this plugin! It’s been really helpful, and I’ve been wanting something like this for a long time.

I have two questions/requests if possible:

1. Could we assign multiple keymaps to exit the ed-cmd? For example, while `<esc>` is the best to enter normal mode, I’d like to sometimes exit using `q` and other times with `<C-c>`.

2. I’m not sure which highlight is linked to ed-cmd, but in some colorschemes, the background highlight for ed-cmd differs from the normal highlight (or the original cmd), which can look off in some cases. Would it be possible to expose the highlight so we can modify it?

The screenshot below illustrates what I mean (with [kanagwa-paper ](https://github.com/sho-87/kanagawa-paper.nvim)colorscheme):
original cmd:
<img width="1224" alt="Screenshot 2024-10-20 at 9 20 37 PM" src="https://github.com/user-attachments/assets/5f39c377-bd86-4eaf-9bf6-8f5e4945572e">

ed-cmd:
<img width="1232" alt="Screenshot 2024-10-20 at 9 21 08 PM" src="https://github.com/user-attachments/assets/90905f40-48d7-4aaa-9830-30db378833ad">

Thanks again

**Comment by smilhey** [comment]
Hello ! You should be able to set multiple keymaps now. I have set the hl-group of the cmdline to MsgArea, does that bring back the default look ?

**Comment by bassamsdata** [comment]
Thank you for the prompt implementation! I can confirm that both features are working well, and the highlight now functions properly across multiple colorschemes with no issues.
