### ISSUE TITLE
Doesn't work well with Neovide

### ISSUE THREAD

**Issue by bassamsdata** [smilhey/ed-cmd.nvim#3]
Hello agian,
yesterday, I tested the plugin with regular Neovim in the terminal since I don’t close Neovide much, but [Neovide](https://github.com/neovide/neovide) is my main app for using Neovim.

It seems like it doesn’t work well with Neovide. I can’t see what I’m typing, and I’m not sure if it’s a z-index issue or something else. (Also, it goes beneath the messages echoed in the command line.)

I’ve tried to show the issue in the video below:

![Kapture 2024-10-21 at 12 24 54](https://github.com/user-attachments/assets/e377fb82-cb62-4fba-b51e-bf636e6092e3)

Thank you!
edit: minor changes

**Comment by bassamsdata** [comment]
By the way, the last 2 commits resolved another issue I was facing when exiting ed-cmd in Neovide. I noticed this while I was writing this issue.

**Comment by smilhey** [comment]
I upped the zindex to match the cmdline popupmenu (can't install neovide right now). Does it solve the issue ?

**Comment by bassamsdata** [comment]
Thank you! It turns out it was indeed a z-index issue, and it's now resolved.
