### ISSUE TITLE
ed-cmd stays in place when switching between horizontal and vertical layouts

### ISSUE THREAD

**Issue by bassamsdata** [smilhey/ed-cmd.nvim#4]
Hello again,

Apologies for keep opening issues! The command line is such an integral part of Neovim, it’s only natural for things to come up.

When switching from a horizontal to vertical layout via the window manager, the ed-cmd staying in place seems. Adding a `VimResized` autocommand might help reposition it properly i think. 

![Kapture 2024-10-21 at 20 34 18](https://github.com/user-attachments/assets/dc536841-9104-4b05-95ae-b32434f1fdeb)

Thanks for considering this!
edit1&2: 1.correcting structure of phrase,2. adding this edit comment.

**Comment by smilhey** [comment]
Hello ! On the contrary, these issues cover the stuff I don't encounter because of my usage so keep them coming. On another note, I was able to reproduce the issue and the last commit solved it for me. Check it out !

**Comment by bassamsdata** [comment]
thank you for the prompt fix, indeed the last commit solved the issue.
